# Generated by Django 4.1.1 on 2023-02-15 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_log_petty_amount_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rgp_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpname', models.CharField(max_length=100)),
                ('dpname', models.CharField(max_length=100)),
                ('spname', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('made_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_status', models.CharField(default='Entry', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
