# Generated by Django 4.1.1 on 2023-02-26 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_nrgp_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgp_entry',
            name='unit',
            field=models.CharField(default=datetime.datetime(2023, 2, 26, 9, 32, 36, 406230, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
