# Generated by Django 4.1.1 on 2023-02-26 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rgp_entry_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrgp_entry',
            name='unit',
            field=models.CharField(default=datetime.datetime(2023, 2, 26, 13, 59, 46, 678985, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
