# Generated by Django 4.0.4 on 2023-03-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_user_rgp_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgp_entry',
            name='approve_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='verify_status',
            field=models.BooleanField(default=False),
        ),
    ]
