# Generated by Django 4.0.4 on 2023-03-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rgp_entry_rgp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgp_entry',
            name='rgp_serial',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
