# Generated by Django 4.0.4 on 2023-03-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rgp_entry_rgp_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgp_entry',
            name='inward_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_receiver', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='inward_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='outward_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outward_sender', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='outward_status',
            field=models.BooleanField(default=False),
        ),
    ]
