# Generated by Django 4.0.4 on 2023-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rgp_entry_inward_receiver_rgp_entry_inward_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgp_entry',
            name='outward_mode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='outward_reciever_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
