# Generated by Django 4.0.4 on 2023-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rgp_entry_outward_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgp_entry',
            name='inward_mode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='inward_party_challan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
