# Generated by Django 4.0.4 on 2023-03-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rgp_entry_inward_mode_rgp_entry_inward_party_challan'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_approve_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrgp_approver', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_outward_mode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_outward_reciever_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_outward_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrgp_outward_sender', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_outward_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_serial',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nrgp_verifier', to='myapp.user_rgp'),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_verify_status',
            field=models.BooleanField(default=False),
        ),
    ]
