# Generated by Django 4.0.4 on 2023-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_nrgp_entry_nrgp_approve_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_approve_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_outward_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nrgp_entry',
            name='nrgp_verify_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='rgp_approve_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='rgp_inward_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='rgp_outward_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rgp_entry',
            name='rgp_verify_time',
            field=models.DateTimeField(null=True),
        ),
    ]
