# Generated by Django 4.0.4 on 2023-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_nrgp_entry_nrgp_approve_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rgp',
            name='department',
            field=models.CharField(choices=[('admin', 'admin'), ('HR', 'HR'), ('QA', 'QA'), ('QC', 'QC')], max_length=100, null=True),
        ),
    ]
